name: CI (Local Test)

on:
  push:
    branches:
      - main

jobs:
  build-test-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest -q
        # ↑ Adds your repo root to Python path so `from app import app` works

      - name: Build Docker image
        run: docker build -t autodeployx:test .

      - name: Run container (for check)
        run: |
          docker run -d -p 5000:5000 autodeployx:test
          sleep 5
          curl -f http://localhost:5000 || (docker logs $(docker ps -lq) && exit 1)
